### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by tek0011** [4pr0n/spambot#1]
Site appears to be down (both https and non secure, even though error below only shows nonsecure, I tried both).  In case no one is currently aware.  My bot is down as well since I use rarchives api to filter spam content.

```
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 502, in <module>
    rarchives_spam_domains = link_filter = get_filter('link') + get_filter('thumb')
  File "info_bot_nsfw.py", line 440, in get_filter
    cache_filters(filter_type)
  File "info_bot_nsfw.py", line 433, in cache_filters
    response = urllib2.urlopen('http://spambot.rarchives.com/api.cgi?method=get_filters&start=0&count=3000&type={0}'.format(filter_type))
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by tek0011** [comment]
Resolved on your end and mine.  Looks like the site is back up, although I see there might still be db issues on it, for now.  I added a cache to my bot, so if the site is down it will no longer attempt to grab links and will use the cached version instead.  It will then check the site every 12 hours to see if its back up.  Just wanted to make this in case owner of site was unaware.
